# Generated by Django 3.1.4 on 2020-12-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boreas_web', '0002_auto_20201227_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='uuid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
